### ISSUE TITLE
Crash via java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by njtxus** [Stormwind99/FoodFunk#32] opened 2018-08-08 17:26 UTC
**Describe the bug**
game crashes after a little while and cannot reload world unless i take off this mod

**Logs**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.11.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  Techguns Core (techguns-1.12.2-2.0.1.1.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.14.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.11-core.jar)
  Wizardry Plugin (wizardry-0.9.3.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b156.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/8/18 1:22 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$ValueIterator.next(Unknown Source)
	at net.minecraft.world.World.func_147448_a(World.java:1943)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:854)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2328822024 bytes (2220 MB) / 6834958336 bytes (6518 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 6 total; -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 8, allocated: 11, tallocated: 96
	FML: MCP 9.42 Powered by Forge 14.23.4.2747 Optifine OptiFine_1.12.2_HD_U_E2 115 mods loaded, 115 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State               | ID                       | Version                 | Source                                            | Signature                                |
	|:------------------- |:------------------------ |:----------------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAAAAAAAAAA | minecraft                | 1.12.2                  | minecraft.jar                                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | mcp                      | 9.42                    | minecraft.jar                                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | FML                      | 8.0.99.99               | forge-1.12.2-14.23.4.2747.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAA | forge                    | 14.23.4.2747            | forge-1.12.2-14.23.4.2747.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAA | ivtoolkit                | 1.3.3-1.12              | minecraft.jar                                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | micdoodlecore            |                         | minecraft.jar                                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | openmodscore             | 0.11.5                  | minecraft.jar                                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | techguns_core            | 1.12.2-1.0              | minecraft.jar                                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | baubles                  | 1.5.2                   | Baubles-1.12-1.5.2.jar                            | None                                     |
	| UCHIJAAAAAAAAAAAAAA | thaumcraft               | 6.1.BETA21              | Thaumcraft-1.12.2-6.1.BETA21.jar                  | None                                     |
	| UCHIJAAAAAAAAAAAAAA | charcoal_pit             | 1.16                    | CharcoalPit-[1.12]-1.16.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | charset                  | 0.5.4.4                 | Charset-Lib-0.5.4.4.jar                           | None                                     |
	| UCHIJAAAAAAAAAAAAAA | crafttweaker             | 4.1.9                   | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAA | mtlib                    | 3.0.5                   | MTLib-3.0.5.jar                                   | None                                     |
	| UCHIJAAAAAAAAAAAAAA | modtweaker               | 4.0.13                  | modtweaker-4.0.13.jar                             | None                                     |
	| UCHIJAAAAAAAAAAAAAA | jei                      | 4.11.0.206              | jei_1.12.2-4.11.0.206.jar                         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | abyssalcraft             | 1.9.4.11                | AbyssalCraft-1.12.2-1.9.4.11.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJAAAAAAAAAAAAAA | codechickenlib           | 3.2.1.350               | CodeChickenLib-1.12.2-3.2.1.350-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAAAAAAA | ancientwarfare           | 1.12.2-2.6.1.298        | ancientwarfare-1.12.2-2.6.1.298.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAA | redstoneflux             | 2.0.2                   | RedstoneFlux-1.12-2.0.2.3-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAAAAAAAAAAAA | ancientwarfareautomation | 1.12.2-2.6.1.298        | ancientwarfare-1.12.2-2.6.1.298.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAA | ancientwarfarenpc        | 1.12.2-2.6.1.298        | ancientwarfare-1.12.2-2.6.1.298.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAA | ancientwarfarestructure  | 1.12.2-2.6.1.298        | ancientwarfare-1.12.2-2.6.1.298.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAA | ancientwarfarevehicle    | 1.12.2-2.6.1.298        | ancientwarfare-1.12.2-2.6.1.298.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAA | applecore                | 3.1.3                   | AppleCore-mc1.12.2-3.1.3.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAA | appleskin                | 1.0.9                   | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | aroma1997core            | 2.0.0.0.b156            | Aroma1997Core-1.12.2-2.0.0.0.b156.jar             | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAAAAAAAAAAAA | aromabackup              | 2.1.1.4.b104            | AromaBackup-1.12.2-2.1.1.4.b104.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAAAAAAAAAAAA | aromabackuprecovery      | 2.1.1.4.b104            | AromaBackup-1.12.2-2.1.1.4.b104.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAAAAAAAAAAAA | astikoor                 | 1.1.1                   | astikoor_horse-carts-1.1.1.jar                    | None                                     |
	| UCHIJAAAAAAAAAAAAAA | wumpleutil               | 2.11.8                  | wumpleutil-1.12.2-2.11.8.jar                      | 1e57901a90acd4a3a54295b6decff5397be51a31 |
	| UCHIJAAAAAAAAAAAAAA | foodfunk                 | 4.4.0                   | foodfunk-1.12.2-4.4.0.jar                         | 1e57901a90acd4a3a54295b6decff5397be51a31 |
	| UCHIJAAAAAAAAAAAAAA | quark                    | r1.4-123                | Quark-r1.4-123.jar                                | None                                     |
	| UCHIJAAAAAAAAAAAAAA | autoreglib               | 1.3-18                  | AutoRegLib-1.3-18.jar                             | None                                     |
	| UCHIJAAAAAAAAAAAAAA | badmobs                  | 1.0.25                  | BadMobs-1.12.2-1.0.25.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAAAAAAAAAAAA | mantle                   | 1.12-1.3.2.24           | Mantle-1.12-1.3.2.24.jar                          | None                                     |
	| UCHIJAAAAAAAAAAAAAA | ctm                      | MC1.12.2-0.3.2.18       | CTM-MC1.12.2-0.3.2.18.jar                         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | chisel                   | MC1.12.2-0.2.0.31       | Chisel-MC1.12.2-0.2.0.31.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAA | toolprogression          | 1.12.2-1.5.4            | toolprogression-1.12.2-1.5.4.jar                  | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| UCHIJAAAAAAAAAAAAAA | tweakersconstruct        | 1.12.2-1.2.0            | tweakersconstruct-1.12.2-1.2.0.jar                | None                                     |
	| UCHIJAAAAAAAAAAAAAA | tconstruct               | 1.12.2-2.10.1.87        | TConstruct-1.12.2-2.10.1.87.jar                   | None                                     |
	| UCHIJAAAAAAAAAAAAAA | bhc                      | 1.2.1                   | baubley-heart-canisters-1.12.2-1.2.1.jar          | None                                     |
	| UCHIJAAAAAAAAAAAAAA | betterfoliage            | 2.1.10                  | BetterFoliage-MC1.12-2.1.10.jar                   | None                                     |
	| UCHIJAAAAAAAAAAAAAA | betterquesting           | 3.5.262                 | BetterQuesting-3.5.262.jar                        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | biomesoplenty            | 7.0.1.2399              | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | campfire                 | 1.2                     | campfire-1.12-v1.2.jar                            | None                                     |
	| UCHIJAAAAAAAAAAAAAA | carryon                  | 1.9.3                   | CarryOn+MC1.12.2+v1.9.3.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | chickenchunks            | 2.4.1.73                | ChickenChunks-1.12.2-2.4.1.73-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAAAAAAA | claybucket               | 1.1                     | ClayBucket-1.12-1.1.jar                           | None                                     |
	| UCHIJAAAAAAAAAAAAAA | cofhcore                 | 4.5.3                   | CoFHCore-1.12.2-4.5.3.20-universal.jar            | None                                     |
	| UCHIJAAAAAAAAAAAAAA | conarm                   | 1.0.2                   | conarm-1.12.2-1.0.2.jar                           | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAAAAAAAAAAAA | cookingforblockheads     | 6.4.44                  | CookingForBlockheads_1.12.2-6.4.44.jar            | None                                     |
	| UCHIJAAAAAAAAAAAAAA | ctgui                    | 1.0.0                   | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAA | crafttweakerjei          | 2.0.2                   | CraftTweaker2-1.12-4.1.9.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAA | dmonsters                | 1.7                     | Deadly+Monsters+1.71.jar                          | None                                     |
	| UCHIJAAAAAAAAAAAAAA | galacticraftcore         | 4.0.1.181               | GalacticraftCore-1.12.2-4.0.1.181.jar             | None                                     |
	| UCHIJAAAAAAAAAAAAAA | dsurround                | 3.4.9.14                | DynamicSurroundings-1.12.2-3.4.9.14.jar           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAAAAAAAAAAAAAA | presets                  | 3.4.9.14                | DynamicSurroundings-1.12.2-3.4.9.14.jar           | None                                     |
	| UCHIJAAAAAAAAAAAAAA | dynamictrees             | 1.12.2-0.7.8            | DynamicTrees-1.12.2-0.7.8.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | dynamictreesbop          | 1.12.2-1.2              | DynamicTreesBOP-1.12.2-1.2.jar                    | None                                     |
	| UCHIJAAAAAAAAAAAAAA | extrautils2              | 1.0                     | extrautils2-1.12-1.8.2.jar                        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | forgelin                 | 1.7.4                   | Forgelin-1.7.4.jar                                | None                                     |
	| UCHIJAAAAAAAAAAAAAA | galacticraftplanets      | 4.0.1.181               | Galacticraft-Planets-1.12.2-4.0.1.181.jar         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | immersiveengineering     | 0.12-84                 | ImmersiveEngineering-0.12-84.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAAAAAAAAAAAA | geolosys                 | 2.0.0                   | Geolosys-1.12.2-2.0.0.jar                         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | gravestone               | 1.0.18                  | GraveStone-1.12.2-Graves-1.0.18.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAA | gravestone-extended      | 1.3.0b7                 | GraveStone-1.12.2-Extended-1.3.0b7.jar            | None                                     |
	| UCHIJAAAAAAAAAAAAAA | hungryanimals            | 1.12.2-5.4.6            | hungryanimals-1.12.2-5.4.6.0.jar                  | None                                     |
	| UCHIJAAAAAAAAAAAAAA | hungrymechanics          | 1.12.2-5.4.0            | hungrymechanics-1.12.2-5.4.0.0.jar                | None                                     |
	| UCHIJAAAAAAAAAAAAAA | waila                    | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | iguanatweaks             | 1.3.9                   | IguanaTweaksReborn-1.3.9-mc1.12.x.jar             | None                                     |
	| UCHIJAAAAAAAAAAAAAA | immersivepetroleum       | 1.1.9                   | immersivepetroleum-1.12.2-1.1.9.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAA | trackapi                 | 1.1                     | TrackAPI-1.1_1.12.jar                             | None                                     |
	| UCHIJAAAAAAAAAAAAAA | immersiverailroading     | 1.3.2                   | ImmersiveRailroading-1.3.2_1.12.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAA | immersivetech            | 1.3.10                  | immersivetech-1.12-1.3.10.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | iymts_mob_mod            | 0.2.0                   | iymts_mob_mod_1.12.2-2611-ver.0.2.0.jar           | None                                     |
	| UCHIJAAAAAAAAAAAAAA | journeymap               | 1.12.2-5.5.2            | journeymap-1.12.2-5.5.2.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | jarm                     | 1.1.2                   | Just+A+Raft+Mod-1.1.2.jar                         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | wizardry                 | 0.9.3                   | wizardry-0.9.3.jar                                | None                                     |
	| UCHIJAAAAAAAAAAAAAA | librarianlib             | 4.11                    | librarianlib-1.12.2-4.11.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAA | modelloader              | 1.0.5                   | modelloader-1.0.5.jar                             | None                                     |
	| UCHIJAAAAAAAAAAAAAA | magneticraft             | 2.4.2                   | Magneticraft_1.12-2.4.2-dev.jar                   | None                                     |
	| UCHIJAAAAAAAAAAAAAA | millenaire               | Millénaire 6.2.8        | millenaire-6.2.8.jar                              | None                                     |
	| UCHIJAAAAAAAAAAAAAA | minecolonies             | 1.12.2-0.9.86-ALPHA     | minecolonies-1.12.2-0.9.86-ALPHA-universal.jar    | None                                     |
	| UCHIJAAAAAAAAAAAAAA | mineralogy               | 3.4.0                   | Mineralogy-1.12-3.4.0.29.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAAAAAAAAAAAA | mtrm                     | 1.2.2.30                | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | mjrlegendslib            | 1.12.2-1.1.5            | MJRLegendsLib-1.12.2-1.1.5.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAAAAAAAAAAAA | monsterswarm             | 2.0.1                   | MonsterSwarm-2.0.1.jar                            | None                                     |
	| UCHIJAAAAAAAAAAAAAA | recipehandler            | 0.11                    | NoMoreRecipeConflict-0.11(1.12.2).jar             | None                                     |
	| UCHIJAAAAAAAAAAAAAA | nei                      | 2.4.1                   | NotEnoughItems-1.12.2-2.4.1.238-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAAAAAAA | openmods                 | 0.11.5                  | OpenModsLib-1.12.2-0.11.5.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAAAAAAAAAAAA | openblocks               | 1.7.6                   | OpenBlocks-1.12.2-1.7.6.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAAAAAAAAAAAA | planetprogression        | 1.12.2-0.2.5            | PlanetProgression-1.12.2-0.2.5.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAAAAAAAAAAAA | pneumaticcraft           | 1.12.2-0.7.5-248        | pneumaticcraft-repressurized-1.12.2-0.7.5-248.jar | None                                     |
	| UCHIJAAAAAAAAAAAAAA | toughasnails             | 3.1.0.128               | ToughAsNails-1.12.2-3.1.0.128-universal.jar       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | thebetweenlands          | 3.3.11                  | TheBetweenlands-3.3.11-universal.jar              | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHIJAAAAAAAAAAAAAA | primal                   | 0.6.68                  | PrimalCore-1.12.2-0.6.68.jar                      | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCHIJAAAAAAAAAAAAAA | reborncore               | 3.9.3.324               | RebornCore-1.12.2-3.9.3.324-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAAAAAAAAAAAA | reccomplex               | 1.4.7                   | RecurrentComplex-1.4.7.jar                        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | sereneseasons            | 1.2.6                   | SereneSeasons-1.12.2-1.2.6-universal.jar          | None                                     |
	| UCHIJAAAAAAAAAAAAAA | spacex                   | 1.0.4                   | spacex-1.12.2-1.0.3.jar                           | None                                     |
	| UCHIJAAAAAAAAAAAAAA | spiceoflife              | 1.3.12                  | SpiceOfLife-mc1.12-1.3.12.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | bq_standard              | 3.4.143                 | StandardExpansion-3.4.143.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | terracore                | 2.1.13                  | TerraCore-1.12-2.1.13.jar                         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | stats_keeper             | 1.12-2.2.9              | StatsKeeper-1.12-2.2.9.jar                        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | stevescarts              | 2.4.22.109              | StevesCarts-1.12.2-2.4.22.109.jar                 | None                                     |
	| UCHIJAAAAAAAAAAAAAA | techguns                 | 2.0.1.1                 | techguns-1.12.2-2.0.1.1.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | tcomplement              | ${version}              | TinkersComplement-1.12.2-0.2.3b.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAA | bspkrscore               | at_0.9                  | TreeCapitator-Mod-1.12.jar                        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | treecapitator            | at_0.9                  | TreeCapitator-Mod-1.12.jar                        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | twilightforest           | 3.7.424                 | twilightforest-1.12.2-3.7.424-universal.jar       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | vc                       | 5.9.13                  | ViesCraft-1.12.2-5.9.13.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | xpfromharvest            | 1.0                     | xpfromharvest-1.12-1.0.1.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAA | hungeroverhaul           | 1.12.2-1.3.3.jenkins148 | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | librarianliblate         | 4.11                    | librarianlib-1.12.2-4.11.jar                      | None                                     |

	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  squeek.applecore.asm.TransformerModuleHandler
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
LibrarianLib Plugin (librarianlib-1.12.2-4.11.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
Techguns Core (techguns-1.12.2-2.0.1.1.jar)
  techguns.core.TechgunsASMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.14.jar)
  org.blockartistry.DynSurround.asm.Transformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.11-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
Wizardry Plugin (wizardry-0.9.3.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b156.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.9.3.324
		Runtime Debofucsation 1
		RenderEngine: 1
	Profiler Position: N/A (disabled)
	Player Count: 2 / 8; [GCEntityPlayerMP['njtxus'/20473, l='a1', x=-317.85, y=71.00, z=409.51], GCEntityPlayerMP['booboolovesyogi'/22464, l='a1', x=278.97, y=74.02, z=178.25]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 398.82
	OpenGlRenderer: GeForce GTX 760/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Config files**
default config

**Comment by Stormwind99** [comment] 2018-08-12 01:12
I can't duplicate this issue, but I suspect I know the cause.

Fixed in WumpleUtil 2.11.12 - update to that version or newer and crash should stop.

Fixed in https://github.com/Stormwind99/WumpleUtil/commit/f9a58aad0843c58a73e62ba79f2cd20eb79fbbdd

**Closed by Stormwind99** 2018-08-12 01:12 UTC
Labels: crash
