### ISSUE TITLE
Abstract decay to use on non-food items

### ISSUE THREAD

**Issue by MessyConfessor** [Stormwind99/FoodFunk#36] opened 2018-08-23 01:54 UTC
**Is your feature request related to a problem? Please describe.**
I'm planning to utilize Food Funk's decay mechanic for some non-food items, but I see that you're planning to implement mechanics like nutrition decay (foods become less filling as they rot). My concern is that, in implementing those mechanics, it may make it impossible to give non-food items decay timers.

**Describe the solution you'd like**
However you implement those mechanics, it would be awesome if they did not cause errors when applied to foods which lack saturation and nutrition values.

**Describe alternatives you've considered**
If that is impossible, perhaps a parallel decay mechanic could be constructed for non-food items, one which does not include the nutrition and saturation multipliers.

**Additional context**
Working on a complex system for a modpack. Food Funk is fantastic.

**Comment by Stormwind99** [comment] 2018-09-17 23:32
I'll keep it in mind, thanks!   Worse case, I'd split the mod into a generic "timed decay" mod and the food oriented one.

**Comment by Stormwind99** [comment] 2019-12-25 21:04
Include with/dupe of #52

**Closed by Stormwind99** 2019-12-25 21:04 UTC
Labels: suggestion
