### ISSUE TITLE
Crash with CoFH Core

### ISSUE THREAD

**Issue by Nacnud4444** [Stormwind99/FoodFunk#61] opened 2019-08-25 17:59 UTC
Game crashes on second launch with CoFH Core installed.

**To Reproduce**
1. Install both FoodFunk and CoFH Core in a modpack on curse/twitch
2. Launch the game
3. Quit the game
4. Launch the game again
5. Observe game crashes (game will continue to crash until modpack is reinstalled)

[latest.log](https://github.com/Stormwind99/FoodFunk/files/3538445/latest.log)

**Comment by iamweirdie** [comment] 2019-10-01 05:21
why didn't anyone post a crashlog?
https://paste.ubuntu.com/p/rN5twJDSkN/
[crash-2019-09-30_22.11.45-client.txt](https://github.com/Stormwind99/FoodFunk/files/3674554/crash-2019-09-30_22.11.45-client.txt)
the git one is in case the other one expires

**Comment by katubug** [comment] 2019-11-17 23:58
I am also having this same issue. I think this issue may be the same one: https://github.com/Stormwind99/FoodFunk/issues/32

But the versions are different. I have:

CofH Core 4.6.3.27
FoodFunk 4.9.5
WumpleUtil 2.12.6

Forge is version 2847 for MC 1.12.2 (obviously lol). There is a temporary workaround when deleting the configs and letting them regen, but as soon as the configs are present, the crash occurs.

**Comment by katubug** [comment] 2019-11-18 00:09
Addendum: deleting the wumpleutil config file only did not seem to affect it. Deleting the foodfunk config prevents the crash. I tried setting various config booleans to their opposite, but none of them made a difference. I didn't edit any non-boolean options.

Finally, in an instance with just CofHCore/dependencies and FoodFunk/WumpleUtil, I enabled debug mode via the FoodFunk config.

latest.log - https://pastebin.com/9NHc53aY
debug.log - https://pastebin.com/rrkKXsjL

**Comment by Stormwind99** [comment] 2019-12-24 23:40
Possibly dupe of #56

**Comment by Stormwind99** [comment] 2019-12-25 04:28
Food Funk 4.9.6 may have a workaround for this crash - can you try it out?  I wasn't able to duplicate the crash afterward with CoFH Core 4.6.3.27.

**Comment by katubug** [comment] 2019-12-25 04:43
I can confirm that loading the new version into my working modlist with CofHCore/World, there is no crash! :)

**Comment by Stormwind99** [comment] 2019-12-25 16:46
Great!  I also just made a workaround in WumpleUtil 2.12.8 that is related to this workaround - would appreciate it if you gave it a try too.

**Comment by katubug** [comment] 2019-12-25 17:14
I updated both when I tested this - would you like me to try them out separately? Also, Merry Christmas!

**Comment by Stormwind99** [comment] 2019-12-25 19:15
Merry Christmas to you too!

Yeah, if you could update both: now Food Funk 4.9.6 and WumpleUtil 2.12.9

**Comment by katubug** [comment] 2019-12-26 00:42
Just to cover all the bases, I did:

- FF 4.9.5 with WU 2.12.7: failure (as expected, as this is what I was using when I reported)
- FF 4.9.6 with WU 2.12.7: success
- FF 4.9.6 with WU 2.12.9: success
- FF 4.9.5 with WU 2.12.9: success

So, this seems pretty thoroughly fixed! If it becomes relevant, I was using my working modlist for this and already generated-and-customized configs. If anything needs to be tested in a more isolated environment, lemme know! :)

**Comment by Stormwind99** [comment] 2019-12-26 01:20
Thanks for testing!

**Closed** 2019-12-26 01:20 UTC
Labels: compatibility, crash

**Comment by katubug** [comment] 2019-12-26 02:30
Happy to help!

**Comment by MagmaSlime123** [comment] 2021-08-30 21:30
> Food Funk 4.9.6 may have a workaround for this crash - can you try it out? I wasn't able to duplicate the crash afterward with CoFH Core 4.6.3.27.

You have 40 issues. Please read them.
